'use strict';

/**
 * Daily Sokoban helpers for the Employee Portal Fun tab.
 * Puzzle of the day is deterministic from the Europe/London date key.
 */

const DIRS = {
  up: { dr: -1, dc: 0 },
  down: { dr: 1, dc: 0 },
  left: { dr: 0, dc: -1 },
  right: { dr: 0, dc: 1 },
};

/**
 * BFS-verified catalog (David W. Skinner Microban / Sasquatch selections).
 * Generated by scripts/buildSokobanCatalog.js — ~90 hard unique layouts.
 */
const LEVELS = require('./sokobanLevels.generated.json').map((level) => ({
  id: level.id,
  title: level.title,
  difficulty: level.difficulty,
  layout: level.layout,
}));

/** Daily rotation excludes the pinned "Box Room" filler so normal days stay hard. */
const ROTATING_LEVELS = LEVELS.filter((level) => level.id !== 'boxroom-1');

const PINNED_BY_DAY = {
  "2026-07-29": "boxroom-1",
};

function getLondonDayKey(date = new Date()) {
  return new Intl.DateTimeFormat('en-CA', {
    timeZone: 'Europe/London',
    year: 'numeric',
    month: '2-digit',
    day: '2-digit',
  }).format(date);
}

function hashString(input) {
  let hash = 2166136261;
  const text = String(input || '');
  for (let i = 0; i < text.length; i += 1) {
    hash ^= text.charCodeAt(i);
    hash = Math.imul(hash, 16777619);
  }
  return hash >>> 0;
}

/** Days since Unix epoch for a YYYY-MM-DD key (UTC noon-safe). */
function dayOrdinal(dayKey) {
  const [year, month, day] = String(dayKey || '').split('-').map(Number);
  return Math.floor(Date.UTC(year, month - 1, day) / 86400000);
}

/** Seeded Fisher–Yates so each level appears once per cycle (no hash clumping). */
function buildPermutation(length, salt) {
  const order = Array.from({ length }, (_, i) => i);
  let seed = hashString(salt);
  const next = () => {
    seed = (Math.imul(seed, 1664525) + 1013904223) >>> 0;
    return seed / 4294967296;
  };
  for (let i = length - 1; i > 0; i -= 1) {
    const j = Math.floor(next() * (i + 1));
    const tmp = order[i];
    order[i] = order[j];
    order[j] = tmp;
  }
  return order;
}

const LEVEL_ORDER = buildPermutation(ROTATING_LEVELS.length, 'sokoban:order:v4');

function keyOf(r, c) {
  return `${r},${c}`;
}

function parseLayout(layout) {
  const rows = layout.map((row) => String(row));
  const height = rows.length;
  const width = Math.max(...rows.map((row) => row.length));
  const walls = new Set();
  const targets = new Set();
  const boxes = new Set();
  let player = null;

  for (let r = 0; r < height; r += 1) {
    const row = rows[r].padEnd(width, ' ');
    for (let c = 0; c < width; c += 1) {
      const ch = row[c];
      if (ch === '#') walls.add(keyOf(r, c));
      if (ch === '.' || ch === '+' || ch === '*') targets.add(keyOf(r, c));
      if (ch === '$' || ch === '*') boxes.add(keyOf(r, c));
      if (ch === '@' || ch === '+') player = { r, c };
    }
  }

  if (!player) {
    throw new Error('Sokoban level is missing a player.');
  }

  return {
    width,
    height,
    walls,
    targets: [...targets],
    boxes: [...boxes].map((k) => {
      const [r, c] = k.split(',').map(Number);
      return { r, c };
    }),
    player,
  };
}

function cloneState(state) {
  return {
    player: { r: state.player.r, c: state.player.c },
    boxes: state.boxes.map((box) => ({ r: box.r, c: box.c })),
  };
}

function boxSet(boxes) {
  return new Set(boxes.map((box) => keyOf(box.r, box.c)));
}

function isWall(puzzle, r, c) {
  if (r < 0 || c < 0 || r >= puzzle.height || c >= puzzle.width) return true;
  return puzzle.walls.has(keyOf(r, c));
}

function isSolved(state, targets) {
  const boxes = boxSet(state.boxes);
  return targets.every((t) => boxes.has(typeof t === 'string' ? t : keyOf(t.r, t.c)));
}

function normalizeDirection(raw) {
  const value = String(raw || '').trim().toLowerCase();
  if (value === 'u' || value === 'w' || value === 'north') return 'up';
  if (value === 'd' || value === 's' || value === 'south') return 'down';
  if (value === 'l' || value === 'a' || value === 'west') return 'left';
  if (value === 'r' || value === 'east') return 'right';
  if (DIRS[value]) return value;
  return '';
}

/**
 * Apply one move. Returns { ok, state, pushed } or { ok:false, reason }.
 */
function applyMove(puzzle, state, direction) {
  const dir = DIRS[normalizeDirection(direction)];
  if (!dir) return { ok: false, reason: 'Invalid direction.' };

  const next = cloneState(state);
  const nr = next.player.r + dir.dr;
  const nc = next.player.c + dir.dc;
  if (isWall(puzzle, nr, nc)) return { ok: false, reason: 'Blocked by wall.' };

  const boxes = boxSet(next.boxes);
  const nextBoxKey = keyOf(nr, nc);
  let pushed = false;

  if (boxes.has(nextBoxKey)) {
    const br = nr + dir.dr;
    const bc = nc + dir.dc;
    if (isWall(puzzle, br, bc) || boxes.has(keyOf(br, bc))) {
      return { ok: false, reason: 'Cannot push box.' };
    }
    next.boxes = next.boxes.map((box) => (
      box.r === nr && box.c === nc ? { r: br, c: bc } : box
    ));
    pushed = true;
  }

  next.player = { r: nr, c: nc };
  return { ok: true, state: next, pushed };
}

function replayMoves(puzzle, moves) {
  let state = {
    player: { ...puzzle.player },
    boxes: puzzle.boxes.map((box) => ({ ...box })),
  };
  const applied = [];
  for (const move of moves || []) {
    const direction = normalizeDirection(move);
    if (!direction) continue;
    const result = applyMove(puzzle, state, direction);
    if (!result.ok) break;
    state = result.state;
    applied.push(direction);
  }
  return { state, moves: applied };
}

function getLevelForDay(dayKey = getLondonDayKey()) {
  const pinnedId = PINNED_BY_DAY[dayKey];
  if (pinnedId) {
    const pinned = LEVELS.find((level) => level.id === pinnedId);
    if (pinned) return pinned;
  }
  if (!ROTATING_LEVELS.length) return LEVELS[0];
  const index = LEVEL_ORDER[dayOrdinal(dayKey) % ROTATING_LEVELS.length];
  return ROTATING_LEVELS[index];
}

function getPuzzleForDay(dayKey = getLondonDayKey()) {
  const level = getLevelForDay(dayKey);
  const parsed = parseLayout(level.layout);
  return {
    puzzleId: level.id,
    title: level.title,
    difficulty: level.difficulty,
    dayKey,
    width: parsed.width,
    height: parsed.height,
    walls: [...parsed.walls],
    targets: parsed.targets,
    initialPlayer: parsed.player,
    initialBoxes: parsed.boxes,
    layout: level.layout,
  };
}

function publicPuzzle(puzzle) {
  return {
    puzzleId: puzzle.puzzleId,
    title: puzzle.title,
    difficulty: puzzle.difficulty,
    dayKey: puzzle.dayKey,
    width: puzzle.width,
    height: puzzle.height,
    walls: puzzle.walls,
    targets: puzzle.targets,
    initialPlayer: puzzle.initialPlayer,
    initialBoxes: puzzle.initialBoxes,
    layout: puzzle.layout,
  };
}

function puzzleEngine(puzzle) {
  return {
    width: puzzle.width,
    height: puzzle.height,
    walls: new Set(puzzle.walls),
    targets: puzzle.targets,
    player: puzzle.initialPlayer,
    boxes: puzzle.initialBoxes,
  };
}

function serializeSokobanGame(data, options = {}) {
  const includePuzzle = Boolean(options.includePuzzle);
  const puzzle = options.puzzle || null;
  return {
    dayKey: data.dayKey || '',
    puzzleId: data.puzzleId || puzzle?.puzzleId || '',
    title: data.title || puzzle?.title || '',
    difficulty: data.difficulty || puzzle?.difficulty || '',
    player: data.player || null,
    boxes: Array.isArray(data.boxes) ? data.boxes : [],
    moves: Array.isArray(data.moves) ? data.moves : [],
    moveCount: Number.isFinite(data.moveCount)
      ? data.moveCount
      : (Array.isArray(data.moves) ? data.moves.length : Number(data.moveCount || 0)),
    resetCount: Number.isFinite(data.resetCount) ? data.resetCount : 0,
    maxResets: Number.isFinite(data.maxResets) ? data.maxResets : null,
    undoCount: Number.isFinite(data.undoCount) ? data.undoCount : 0,
    maxUndos: Number.isFinite(data.maxUndos) ? data.maxUndos : null,
    status: data.status || 'in_progress',
    completedAt: data.completedAt?.toDate?.()?.toISOString?.() || data.completedAt || null,
    ...(includePuzzle && puzzle ? { puzzle: publicPuzzle(puzzle) } : {}),
  };
}

function createInitialGame(puzzle, dayKey) {
  return {
    dayKey,
    puzzleId: puzzle.puzzleId,
    title: puzzle.title,
    difficulty: puzzle.difficulty,
    player: { ...puzzle.initialPlayer },
    boxes: puzzle.initialBoxes.map((box) => ({ ...box })),
    moves: [],
    moveCount: 0,
    resetCount: 0,
    maxResets: null,
    undoCount: 0,
    maxUndos: null,
    status: 'in_progress',
  };
}

function shiftDayKey(dayKey, deltaDays) {
  const [year, month, day] = String(dayKey || '').split('-').map(Number);
  const date = new Date(Date.UTC(year, month - 1, day, 12));
  date.setUTCDate(date.getUTCDate() + deltaDays);
  return date.toISOString().slice(0, 10);
}

/**
 * Admin schedule preview for the next N days (including today by default).
 */
function listUpcomingPuzzles(fromDayKey = getLondonDayKey(), days = 21) {
  const count = Math.max(1, Math.min(60, Number(days) || 21));
  const start = fromDayKey || getLondonDayKey();
  const rows = [];
  for (let i = 0; i < count; i += 1) {
    const dayKey = shiftDayKey(start, i);
    const puzzle = getPuzzleForDay(dayKey);
    rows.push({
      dayKey,
      puzzleId: puzzle.puzzleId,
      title: puzzle.title,
      difficulty: puzzle.difficulty,
      width: puzzle.width,
      height: puzzle.height,
      pinned: Boolean(PINNED_BY_DAY[dayKey]),
    });
  }
  return rows;
}

module.exports = {
  LEVELS,
  DIRS,
  getLondonDayKey,
  getLevelForDay,
  getPuzzleForDay,
  listUpcomingPuzzles,
  publicPuzzle,
  puzzleEngine,
  applyMove,
  replayMoves,
  normalizeDirection,
  isSolved,
  serializeSokobanGame,
  createInitialGame,
  parseLayout,
  shiftDayKey,
};
